## Preprocessing

In [13]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf


#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("degree_data.csv")
application_df

,2020 National Employment Matrix title,Typical education needed for entry,Less than high school diploma,High school diploma or equivalent,"Some college, no degree",Associates degree,Bachelors degree,Masters degree,Doctoral or professional degree
0,Chief executives(1),Bachelors degree,1.5,8.3,14.2,5.1,40.5,23.7,6.7
1,General and operations managers,Bachelors degree,2.6,17.0,24.8,9.8,33.0,11.1,1.6
2,Legislators(1),Bachelors degree,1.5,8.3,14.2,5.1,40.5,23.7,6.7
3,Advertising and promotions managers,Bachelors degree,0.8,3.9,10.8,6.0,63.6,12.8,2.1
4,Marketing managers,Bachelors degree,0.7,3.8,9.3,5.0,55.8,23.5,2.0
...,...,...,...,...,...,...,...,...,...
789,"Material moving workers, all other(1)",No formal educational credential,19.8,48.2,19.1,6.2,5.7,0.8,0.1
790,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
791,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
793,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
application_df = application_df.dropna()

In [15]:
application_df

,2020 National Employment Matrix title,Typical education needed for entry,Less than high school diploma,High school diploma or equivalent,"Some college, no degree",Associates degree,Bachelors degree,Masters degree,Doctoral or professional degree
0,Chief executives(1),Bachelors degree,1.5,8.3,14.2,5.1,40.5,23.7,6.7
1,General and operations managers,Bachelors degree,2.6,17.0,24.8,9.8,33.0,11.1,1.6
2,Legislators(1),Bachelors degree,1.5,8.3,14.2,5.1,40.5,23.7,6.7
3,Advertising and promotions managers,Bachelors degree,0.8,3.9,10.8,6.0,63.6,12.8,2.1
4,Marketing managers,Bachelors degree,0.7,3.8,9.3,5.0,55.8,23.5,2.0
...,...,...,...,...,...,...,...,...,...
785,"Pump operators, except wellhead pumpers(1)",High school diploma or equivalent,14.0,43.8,22.3,7.7,10.0,2.2,0.0
786,Wellhead pumpers(1),High school diploma or equivalent,14.0,43.8,22.3,7.7,10.0,2.2,0.0
787,Refuse and recyclable material collectors,No formal educational credential,23.3,46.9,18.0,5.0,6.3,0.3,0.1
788,"Tank car, truck, and ship loaders(1)",No formal educational credential,19.8,48.2,19.1,6.2,5.7,0.8,0.1
789,"Material moving workers, all other(1)",No formal educational credential,19.8,48.2,19.1,6.2,5.7,0.8,0.1

In [16]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
for x in application_df.columns:
    print(x, len(application_df[x].unique()))

2020 National Employment Matrix title 790
Typical education needed for entry 8
Less than high school diploma 197
High school diploma or equivalent 327
Some college, no degree 268
Associates degree 179
Bachelors degree 330
Masters degree 212
Doctoral or professional degree 106

In [4]:
# # Look at APPLICATION_TYPE value counts for binning
# #  YOUR CODE GOES HERE
# bin_counts = application_df['APPLICATION_TYPE'].value_counts()
# bin_counts

In [5]:
# # Choose a cutoff value and create a list of application types to be replaced
# # use the variable name `application_types_to_replace`
# #  YOUR CODE GOES HERE
# application_types_to_replace = list(bin_counts[bin_counts<500].index)
# application_types_to_replace

# # Replace in dataframe
# for app in application_types_to_replace:
#     application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# # Check to make sure binning was successful
# application_df['APPLICATION_TYPE'].value_counts()

In [6]:
# # Look at CLASSIFICATION value counts for binning
# #  YOUR CODE GOES HERE
# class_binning = application_df['CLASSIFICATION'].value_counts()
# class_binning

In [7]:
# # You may find it helpful to look at CLASSIFICATION value counts >1
# #  YOUR CODE GOES HERE
# counts_class = class_binning[class_binning>1]
# counts_class

In [8]:
# # Choose a cutoff value and create a list of classifications to be replaced
# # use the variable name `classifications_to_replace`
# #  YOUR CODE GOES HERE
# classifications_to_replace = list (counts_class[counts_class<100].index)
# classifications_to_replace

# # Replace in dataframe
# for cls in classifications_to_replace:
#     application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# # Check to make sure binning was successful
# application_df['CLASSIFICATION'].value_counts()

In [17]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,Less than high school diploma,High school diploma or equivalent,"Some college, no degree",Associates degree,Bachelors degree,Masters degree,Doctoral or professional degree,2020 National Employment Matrix title_Accountants and auditors,2020 National Employment Matrix title_Actors,2020 National Employment Matrix title_Actuaries,...,2020 National Employment Matrix title_Writers and authors,2020 National Employment Matrix title_Zoologists and wildlife biologists(1),Typical education needed for entry_Associates degree,Typical education needed for entry_Bachelors degree,Typical education needed for entry_Doctoral or professional degree,Typical education needed for entry_High school diploma or equivalent,Typical education needed for entry_Masters degree,Typical education needed for entry_No formal educational credential,Typical education needed for entry_Postsecondary nondegree award,"Typical education needed for entry_Some college, no degree"
0,1.5,8.3,14.2,5.1,40.5,23.7,6.7,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2.6,17.0,24.8,9.8,33.0,11.1,1.6,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.5,8.3,14.2,5.1,40.5,23.7,6.7,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.8,3.9,10.8,6.0,63.6,12.8,2.1,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.7,3.8,9.3,5.0,55.8,23.5,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
y = application_df['Typical education needed for entry_Bachelors degree'].values
X = application_df.drop('Typical education needed for entry_Bachelors degree', axis=1).values
print(y)
print(X)
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 0. 0. 1. 1. 0.
 0. 0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1.
 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 1. 0. 1. 0.
 1. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[ 1.5  8.3 14.2 ...  0.   0.   0. ]
 [ 2.6 17.  24.8 ...  0.   0.   0. ]
 [ 1.5  8.3 14.2 ...  0.   0.   0. ]
 ...
 [23.3 46.9 18.  ...  1.   0.   0. ]
 [19.8 48.2 19.1 ...  1.   0.   0. ]
 [19.8 48.2 19.1 ...  1.   0.   0. ]]

In [19]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [20]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=7
hidden_nodes_layer2=14
hidden_nodes_layer3=21

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))
# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))
# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 7)                 5635

 dense_1 (Dense)             (None, 14)                112

 dense_2 (Dense)             (None, 1)                 15

=================================================================
Total params: 5,762
Trainable params: 5,762
Non-trainable params: 0
_________________________________________________________________

In [21]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [22]:
# Train the model
#  YOUR CODE GOES 
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
16/16 [==============================] - 1s 16ms/step - loss: 0.7244 - accuracy: 0.4771 - val_loss: 0.6975 - val_accuracy: 0.5955
Epoch 2/100
16/16 [==============================] - 0s 5ms/step - loss: 0.6155 - accuracy: 0.7416 - val_loss: 0.6457 - val_accuracy: 0.7191
Epoch 3/100
16/16 [==============================] - 0s 6ms/step - loss: 0.5377 - accuracy: 0.7833 - val_loss: 0.6092 - val_accuracy: 0.7303
Epoch 4/100
16/16 [==============================] - 0s 3ms/step - loss: 0.4772 - accuracy: 0.8072 - val_loss: 0.5784 - val_accuracy: 0.7528
Epoch 5/100
16/16 [==============================] - 0s 4ms/step - loss: 0.4214 - accuracy: 0.8270 - val_loss: 0.5500 - val_accuracy: 0.7416
Epoch 6/100
16/16 [==============================] - 0s 4ms/step - loss: 0.3664 - accuracy: 0.8489 - val_loss: 0.5255 - val_accuracy: 0.7528
Epoch 7/100
16/16 [==============================] - 0s 4ms/step - loss: 0.3129 - accuracy: 0.8867 - val_loss: 0.5033 - val_accuracy: 0.7640
Epoch 8/100
16/16 [==============================] - 0s 4ms/step - loss: 0.2644 - accuracy: 0.9085 - val_loss: 0.4843 - val_accuracy: 0.7640
Epoch 9/100
16/16 [==============================] - 0s 5ms/step - loss: 0.2230 - accuracy: 0.9284 - val_loss: 0.4682 - val_accuracy: 0.7640
Epoch 10/100
16/16 [==============================] - 0s 3ms/step - loss: 0.1894 - accuracy: 0.9384 - val_loss: 0.4567 - val_accuracy: 0.7753
Epoch 11/100
16/16 [==============================] - 0s 4ms/step - loss: 0.1627 - accuracy: 0.9404 - val_loss: 0.4492 - val_accuracy: 0.7978
Epoch 12/100
16/16 [==============================] - 0s 5ms/step - loss: 0.1406 - accuracy: 0.9443 - val_loss: 0.4425 - val_accuracy: 0.7978
Epoch 13/100
16/16 [==============================] - 0s 5ms/step - loss: 0.1240 - accuracy: 0.9463 - val_loss: 0.4368 - val_accuracy: 0.8090
Epoch 14/100
16/16 [==============================] - 0s 4ms/step - loss: 0.1100 - accuracy: 0.9483 - val_loss: 0.4313 - val_accuracy: 0.8090
Epoch 15/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0980 - accuracy: 0.9523 - val_loss: 0.4285 - val_accuracy: 0.8202
Epoch 16/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0889 - accuracy: 0.9523 - val_loss: 0.4248 - val_accuracy: 0.8202
Epoch 17/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0812 - accuracy: 0.9543 - val_loss: 0.4218 - val_accuracy: 0.8202
Epoch 18/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0751 - accuracy: 0.9543 - val_loss: 0.4192 - val_accuracy: 0.8202
Epoch 19/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0695 - accuracy: 0.9543 - val_loss: 0.4183 - val_accuracy: 0.8202
Epoch 20/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0653 - accuracy: 0.9543 - val_loss: 0.4181 - val_accuracy: 0.8202
Epoch 21/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0616 - accuracy: 0.9543 - val_loss: 0.4174 - val_accuracy: 0.8202
Epoch 22/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0585 - accuracy: 0.9543 - val_loss: 0.4183 - val_accuracy: 0.8202
Epoch 23/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0556 - accuracy: 0.9543 - val_loss: 0.4206 - val_accuracy: 0.8315
Epoch 24/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0531 - accuracy: 0.9543 - val_loss: 0.4214 - val_accuracy: 0.8202
Epoch 25/100
16/16 [==============================] - 0s 3ms/step - loss: 0.0508 - accuracy: 0.9543 - val_loss: 0.4228 - val_accuracy: 0.8202
Epoch 26/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0489 - accuracy: 0.9543 - val_loss: 0.4252 - val_accuracy: 0.8202
Epoch 27/100
16/16 [==============================] - 0s 3ms/step - loss: 0.0471 - accuracy: 0.9543 - val_loss: 0.4269 - val_accuracy: 0.8315
Epoch 28/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0454 - accuracy: 0.9622 - val_loss: 0.4300 - val_accuracy: 0.8202
Epoch 29/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0439 - accuracy: 0.9940 - val_loss: 0.4340 - val_accuracy: 0.8202
Epoch 30/100
16/16 [==============================] - 0s 3ms/step - loss: 0.0426 - accuracy: 0.9940 - val_loss: 0.4368 - val_accuracy: 0.8202
Epoch 31/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0413 - accuracy: 0.9940 - val_loss: 0.4387 - val_accuracy: 0.8202
Epoch 32/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0401 - accuracy: 0.9940 - val_loss: 0.4437 - val_accuracy: 0.8202
Epoch 33/100
16/16 [==============================] - 0s 3ms/step - loss: 0.0390 - accuracy: 0.9940 - val_loss: 0.4488 - val_accuracy: 0.8090
Epoch 34/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0380 - accuracy: 0.9940 - val_loss: 0.4540 - val_accuracy: 0.7978
Epoch 35/100
16/16 [==============================] - 0s 3ms/step - loss: 0.0370 - accuracy: 0.9940 - val_loss: 0.4580 - val_accuracy: 0.7865
Epoch 36/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0361 - accuracy: 0.9940 - val_loss: 0.4607 - val_accuracy: 0.8090
Epoch 37/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0354 - accuracy: 0.9940 - val_loss: 0.4634 - val_accuracy: 0.8090
Epoch 38/100
16/16 [==============================] - 0s 3ms/step - loss: 0.0346 - accuracy: 0.9940 - val_loss: 0.4676 - val_accuracy: 0.8090
Epoch 39/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0340 - accuracy: 0.9940 - val_loss: 0.4716 - val_accuracy: 0.7978
Epoch 40/100
16/16 [==============================] - 0s 3ms/step - loss: 0.0333 - accuracy: 0.9940 - val_loss: 0.4754 - val_accuracy: 0.7978
Epoch 41/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0327 - accuracy: 0.9940 - val_loss: 0.4797 - val_accuracy: 0.7978
Epoch 42/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0321 - accuracy: 0.9940 - val_loss: 0.4855 - val_accuracy: 0.7865
Epoch 43/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0316 - accuracy: 0.9940 - val_loss: 0.4913 - val_accuracy: 0.7528
Epoch 44/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0311 - accuracy: 0.9940 - val_loss: 0.4967 - val_accuracy: 0.7528
Epoch 45/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0306 - accuracy: 0.9940 - val_loss: 0.5016 - val_accuracy: 0.7528
Epoch 46/100
16/16 [==============================] - 0s 3ms/step - loss: 0.0301 - accuracy: 0.9940 - val_loss: 0.5067 - val_accuracy: 0.7528
Epoch 47/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0297 - accuracy: 0.9940 - val_loss: 0.5098 - val_accuracy: 0.7528
Epoch 48/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0292 - accuracy: 0.9940 - val_loss: 0.5135 - val_accuracy: 0.7528
Epoch 49/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0289 - accuracy: 0.9940 - val_loss: 0.5186 - val_accuracy: 0.7528
Epoch 50/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0285 - accuracy: 0.9940 - val_loss: 0.5238 - val_accuracy: 0.7416
Epoch 51/100
16/16 [==============================] - 0s 3ms/step - loss: 0.0281 - accuracy: 0.9940 - val_loss: 0.5281 - val_accuracy: 0.7303
Epoch 52/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0278 - accuracy: 0.9940 - val_loss: 0.5333 - val_accuracy: 0.7303
Epoch 53/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0274 - accuracy: 0.9940 - val_loss: 0.5388 - val_accuracy: 0.7191
Epoch 54/100
16/16 [==============================] - 0s 3ms/step - loss: 0.0271 - accuracy: 0.9940 - val_loss: 0.5451 - val_accuracy: 0.7191
Epoch 55/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0267 - accuracy: 0.9940 - val_loss: 0.5502 - val_accuracy: 0.7191
Epoch 56/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0264 - accuracy: 0.9940 - val_loss: 0.5567 - val_accuracy: 0.7191
Epoch 57/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0261 - accuracy: 0.9940 - val_loss: 0.5636 - val_accuracy: 0.7191
Epoch 58/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0258 - accuracy: 0.9940 - val_loss: 0.5692 - val_accuracy: 0.7191
Epoch 59/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0255 - accuracy: 0.9940 - val_loss: 0.5766 - val_accuracy: 0.7191
Epoch 60/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0252 - accuracy: 0.9940 - val_loss: 0.5830 - val_accuracy: 0.7191
Epoch 61/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0250 - accuracy: 0.9940 - val_loss: 0.5881 - val_accuracy: 0.7191
Epoch 62/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0247 - accuracy: 0.9940 - val_loss: 0.5927 - val_accuracy: 0.7191
Epoch 63/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0244 - accuracy: 0.9940 - val_loss: 0.5984 - val_accuracy: 0.7191
Epoch 64/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0242 - accuracy: 0.9940 - val_loss: 0.6066 - val_accuracy: 0.7191
Epoch 65/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0239 - accuracy: 0.9940 - val_loss: 0.6139 - val_accuracy: 0.7079
Epoch 66/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0237 - accuracy: 0.9940 - val_loss: 0.6213 - val_accuracy: 0.6966
Epoch 67/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0235 - accuracy: 0.9940 - val_loss: 0.6297 - val_accuracy: 0.6629
Epoch 68/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0232 - accuracy: 0.9940 - val_loss: 0.6342 - val_accuracy: 0.6629
Epoch 69/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0230 - accuracy: 0.9940 - val_loss: 0.6403 - val_accuracy: 0.6629
Epoch 70/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0228 - accuracy: 0.9940 - val_loss: 0.6481 - val_accuracy: 0.6629
Epoch 71/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0227 - accuracy: 0.9940 - val_loss: 0.6543 - val_accuracy: 0.6629
Epoch 72/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0224 - accuracy: 0.9940 - val_loss: 0.6610 - val_accuracy: 0.6629
Epoch 73/100
16/16 [==============================] - 0s 3ms/step - loss: 0.0223 - accuracy: 0.9940 - val_loss: 0.6698 - val_accuracy: 0.6629
Epoch 74/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0221 - accuracy: 0.9940 - val_loss: 0.6783 - val_accuracy: 0.6629
Epoch 75/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0219 - accuracy: 0.9940 - val_loss: 0.6836 - val_accuracy: 0.6629
Epoch 76/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0217 - accuracy: 0.9940 - val_loss: 0.6898 - val_accuracy: 0.6629
Epoch 77/100
16/16 [==============================] - 0s 3ms/step - loss: 0.0216 - accuracy: 0.9940 - val_loss: 0.6988 - val_accuracy: 0.6629
Epoch 78/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0214 - accuracy: 0.9940 - val_loss: 0.7060 - val_accuracy: 0.6629
Epoch 79/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0213 - accuracy: 0.9940 - val_loss: 0.7127 - val_accuracy: 0.6629
Epoch 80/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0212 - accuracy: 0.9940 - val_loss: 0.7204 - val_accuracy: 0.6629
Epoch 81/100
16/16 [==============================] - 0s 3ms/step - loss: 0.0210 - accuracy: 0.9940 - val_loss: 0.7244 - val_accuracy: 0.6517
Epoch 82/100
16/16 [==============================] - 0s 3ms/step - loss: 0.0209 - accuracy: 0.9940 - val_loss: 0.7308 - val_accuracy: 0.6517
Epoch 83/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0208 - accuracy: 0.9940 - val_loss: 0.7387 - val_accuracy: 0.6517
Epoch 84/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0207 - accuracy: 0.9940 - val_loss: 0.7449 - val_accuracy: 0.6517
Epoch 85/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0206 - accuracy: 0.9940 - val_loss: 0.7511 - val_accuracy: 0.6404
Epoch 86/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0205 - accuracy: 0.9940 - val_loss: 0.7572 - val_accuracy: 0.6067
Epoch 87/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0204 - accuracy: 0.9940 - val_loss: 0.7605 - val_accuracy: 0.6067
Epoch 88/100
16/16 [==============================] - 0s 3ms/step - loss: 0.0203 - accuracy: 0.9940 - val_loss: 0.7687 - val_accuracy: 0.6067
Epoch 89/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0202 - accuracy: 0.9940 - val_loss: 0.7724 - val_accuracy: 0.6067
Epoch 90/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0201 - accuracy: 0.9940 - val_loss: 0.7800 - val_accuracy: 0.6067
Epoch 91/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0200 - accuracy: 0.9940 - val_loss: 0.7865 - val_accuracy: 0.6067
Epoch 92/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0200 - accuracy: 0.9940 - val_loss: 0.7951 - val_accuracy: 0.5955
Epoch 93/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0199 - accuracy: 0.9940 - val_loss: 0.8023 - val_accuracy: 0.5955
Epoch 94/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0198 - accuracy: 0.9940 - val_loss: 0.8071 - val_accuracy: 0.5955
Epoch 95/100
16/16 [==============================] - 0s 3ms/step - loss: 0.0197 - accuracy: 0.9940 - val_loss: 0.8113 - val_accuracy: 0.5955
Epoch 96/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0197 - accuracy: 0.9940 - val_loss: 0.8156 - val_accuracy: 0.5955
Epoch 97/100
16/16 [==============================] - 0s 3ms/step - loss: 0.0197 - accuracy: 0.9940 - val_loss: 0.8252 - val_accuracy: 0.5955
Epoch 98/100
16/16 [==============================] - 0s 5ms/step - loss: 0.0196 - accuracy: 0.9940 - val_loss: 0.8302 - val_accuracy: 0.5955
Epoch 99/100
16/16 [==============================] - 0s 4ms/step - loss: 0.0195 - accuracy: 0.9940 - val_loss: 0.8369 - val_accuracy: 0.5843
Epoch 100/100
16/16 [==============================] - 0s 3ms/step - loss: 0.0195 - accuracy: 0.9940 - val_loss: 0.8427 - val_accuracy: 0.5843

In [23]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

7/7 - 0s - loss: 0.1583 - accuracy: 0.9495 - 26ms/epoch - 4ms/step
Loss: 0.1582973748445511, Accuracy: 0.9494949579238892

In [ ]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
from google.colab import files
nn.save('/content/AlphabetSoupCharity.h5')
files.download('/content/AlphabetSoupCharity.h5')